// <auto-generated />
using System;
using Electronic_Election_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Electronic_Election_Management_System.Migrations
{
    [DbContext(typeof(ElectionDbContext))]
    [Migration("20260707072655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Electronic_Election_Management_System.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ElectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CastAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VoteTokenId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoteTokenId")
                        .IsUnique();

                    b.ToTable("Votes", t =>
                        {
                            t.HasCheckConstraint("CK_Votes_ExactlyOneVoterIdentity", "((VoteTokenId IS NOT NULL AND UserId IS NULL) OR (VoteTokenId IS NULL AND UserId IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.VoteToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId", "ElectionId")
                        .IsUnique();

                    b.ToTable("VoteTokens");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.AuditLog", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Election", "Election")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Election", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.User", "CreatedByUser")
                        .WithMany("ElectionsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Option", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Election", "Election")
                        .WithMany("Options")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Vote", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Option", "Option")
                        .WithMany("Votes")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Election_Management_System.Models.VoteToken", "VoteToken")
                        .WithOne("Vote")
                        .HasForeignKey("Electronic_Election_Management_System.Models.Vote", "VoteTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Option");

                    b.Navigation("User");

                    b.Navigation("VoteToken");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.VoteToken", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Election", "Election")
                        .WithMany("VoteTokens")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithMany("VoteTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Election", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Options");

                    b.Navigation("VoteTokens");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Option", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ElectionsCreated");

                    b.Navigation("VoteTokens");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.VoteToken", b =>
                {
                    b.Navigation("Vote");
                });
#pragma warning restore 612, 618
        }
    }
}
