// <auto-generated />
using System;
using Electronic_Election_Management_System.Data.DesignTime;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Electronic_Election_Management_System.Migrations.Postgres
{
    [DbContext(typeof(PostgresAppDbContext))]
    [Migration("20260818171920_AddScoringSchemesAndLatestChanges")]
    partial class AddScoringSchemesAndLatestChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Electronic_Election_Management_System.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudienceGroupsSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.ElectionInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ElectionId", "Email")
                        .IsUnique();

                    b.ToTable("ElectionInvitations");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.ElectionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMultipleAnswers")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowOtherOption")
                        .HasColumnType("boolean");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageDataUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RequiredRankCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScoringSchemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ScoringSchemeId");

                    b.ToTable("ElectionQuestions");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageDataUrl")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.ScoringScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLinear")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPredefined")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Points")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ScoringSchemes");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.UserDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Citizenship")
                        .HasColumnType("text");

                    b.Property<string>("Cnp")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("ResidenceAddress")
                        .HasColumnType("text");

                    b.Property<string>("ResidenceCity")
                        .HasColumnType("text");

                    b.Property<string>("ResidenceCounty")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkEmail")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.UserLabel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "LabelId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("LabelId");

                    b.ToTable("UserLabels");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<DateTime>("CastAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VoteTokenId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoteTokenId");

                    b.ToTable("Votes", t =>
                        {
                            t.HasCheckConstraint("CK_Votes_ExactlyOneAnswerKind", "((\"OptionId\" IS NOT NULL AND \"QuestionId\" IS NULL AND \"AnswerText\" IS NULL) OR (\"OptionId\" IS NULL AND \"QuestionId\" IS NOT NULL AND \"AnswerText\" IS NOT NULL))");

                            t.HasCheckConstraint("CK_Votes_ExactlyOneVoterIdentity", "((\"VoteTokenId\" IS NOT NULL AND \"UserId\" IS NULL) OR (\"VoteTokenId\" IS NULL AND \"UserId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.VoteToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId", "ElectionId")
                        .IsUnique();

                    b.ToTable("VoteTokens");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.VoterChangeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChangeCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId", "ElectionId")
                        .IsUnique();

                    b.ToTable("VoterChangeRecords");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.VoterDeclaration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Citizenship")
                        .HasColumnType("text");

                    b.Property<string>("Cnp")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("ResidenceAddress")
                        .HasColumnType("text");

                    b.Property<string>("ResidenceCity")
                        .HasColumnType("text");

                    b.Property<string>("ResidenceCounty")
                        .HasColumnType("text");

                    b.Property<Guid>("VoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkEmail")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VoteId")
                        .IsUnique();

                    b.ToTable("VoterDeclarations");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.AuditLog", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Election", "Election")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Election", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.User", "CreatedByUser")
                        .WithMany("ElectionsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.ElectionInvitation", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Election", "Election")
                        .WithMany("Invitations")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithMany("ElectionInvitations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.ElectionQuestion", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Election", "Election")
                        .WithMany("Questions")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electronic_Election_Management_System.Models.ScoringScheme", "ScoringScheme")
                        .WithMany()
                        .HasForeignKey("ScoringSchemeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Election");

                    b.Navigation("ScoringScheme");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Notification", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Option", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Election", "Election")
                        .WithMany("Options")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electronic_Election_Management_System.Models.ElectionQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Election");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.ScoringScheme", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.UserDetails", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithOne("UserDetails")
                        .HasForeignKey("Electronic_Election_Management_System.Models.UserDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.UserLabel", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Electronic_Election_Management_System.Models.Label", "Label")
                        .WithMany("UserLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithMany("UserLabels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Label");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Vote", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Option", "Option")
                        .WithMany("Votes")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Electronic_Election_Management_System.Models.ElectionQuestion", "Question")
                        .WithMany("Votes")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Election_Management_System.Models.VoteToken", "VoteToken")
                        .WithMany("Votes")
                        .HasForeignKey("VoteTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Option");

                    b.Navigation("Question");

                    b.Navigation("User");

                    b.Navigation("VoteToken");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.VoteToken", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Election", "Election")
                        .WithMany("VoteTokens")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithMany("VoteTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.VoterChangeRecord", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electronic_Election_Management_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.VoterDeclaration", b =>
                {
                    b.HasOne("Electronic_Election_Management_System.Models.Vote", "Vote")
                        .WithOne("VoterDeclaration")
                        .HasForeignKey("Electronic_Election_Management_System.Models.VoterDeclaration", "VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vote");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Election", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Invitations");

                    b.Navigation("Options");

                    b.Navigation("Questions");

                    b.Navigation("VoteTokens");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.ElectionQuestion", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Label", b =>
                {
                    b.Navigation("UserLabels");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Option", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ElectionInvitations");

                    b.Navigation("ElectionsCreated");

                    b.Navigation("Notifications");

                    b.Navigation("UserDetails");

                    b.Navigation("UserLabels");

                    b.Navigation("VoteTokens");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.Vote", b =>
                {
                    b.Navigation("VoterDeclaration");
                });

            modelBuilder.Entity("Electronic_Election_Management_System.Models.VoteToken", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
